//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbitrage_Client.ForkService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ForkService.IArbitrageService")]
    public interface IArbitrageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArbitrageService/GetArbitrageList", ReplyAction="http://tempuri.org/IArbitrageService/GetArbitrageListResponse")]
        string GetArbitrageList(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArbitrageService/GetArbitrageList", ReplyAction="http://tempuri.org/IArbitrageService/GetArbitrageListResponse")]
        System.Threading.Tasks.Task<string> GetArbitrageListAsync(string filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArbitrageServiceChannel : Arbitrage_Client.ForkService.IArbitrageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArbitrageServiceClient : System.ServiceModel.ClientBase<Arbitrage_Client.ForkService.IArbitrageService>, Arbitrage_Client.ForkService.IArbitrageService {
        
        public ArbitrageServiceClient() {
        }
        
        public ArbitrageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArbitrageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArbitrageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArbitrageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetArbitrageList(string filter) {
            return base.Channel.GetArbitrageList(filter);
        }
        
        public System.Threading.Tasks.Task<string> GetArbitrageListAsync(string filter) {
            return base.Channel.GetArbitrageListAsync(filter);
        }
    }
}
